# Generated by Django 5.0 on 2024-01-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate_code',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
