# Generated by Django 5.0 on 2024-01-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_activate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_active',
            field=models.BooleanField(default=False),
        ),
    ]
